tools:
  golint:
    enabled: true
    blacklisted_files: '.*\/vendor\/.*'
  staticcheck:
    enabled: true
  go vet:
    enabled: true
  gosec:
    enabled: true
  golangci-lint:
    enabled: true
    execution_directory: 'spec/fixtures/test.git'
