name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t pronto-golang .

    - name: Test
      run: docker-compose run --rm -T pronto-golang bundle exec rspec --format documentation --color
